version: '2'
services:
  github-webhook-server:
    build: .
    image: garcianavalon/github-webhook-server
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    # nodemon for live reloading in development
    command: [nodemon, ./bin/www]